export interface Drug {
  name: string;
  aliases: string[];
  purpose: string;
}

/** `aliases` always starts with the lower-case generic name, followed by common Indian brand names. */
const d = (name: string, purpose: string, ...brands: string[]): Drug => ({ name, purpose, aliases: [name.toLowerCase(), ...brands] });

/**
 * Common medicines on Indian prescriptions: generic (INN) names plus widely used brand names.
 * Hand-assembled from general knowledge, not copied from a dataset. It is for recognising what a prescription
 * says, NOT clinical advice, and should be reviewed by a pharmacist before anyone relies on it.
 * Aliases are matched as whole words, so keep them at four letters or more and never a plain English word.
 */
export const DRUGS: Drug[] = [
  // pain and fever
  d('Paracetamol', 'Fever / pain', 'dolo', 'crocin', 'calpol', 'acetaminophen'),
  d('Ibuprofen', 'Pain relief', 'brufen', 'combiflam'),
  d('Diclofenac', 'Pain relief', 'voveran', 'voltaren'),
  d('Aceclofenac', 'Pain relief', 'zerodol', 'hifenac'),
  d('Naproxen', 'Pain relief', 'naprosyn'),
  d('Etoricoxib', 'Pain relief', 'nucoxia', 'arcoxia'),
  d('Ketorolac', 'Pain relief', 'ketorol'),
  d('Nimesulide', 'Pain relief', 'nimulid'),
  d('Mefenamic acid', 'Pain relief', 'meftal'),
  d('Tramadol', 'Pain relief', 'tramazac'),
  d('Aspirin', 'Heart protection', 'ecosprin', 'disprin'),
  d('Thiocolchicoside', 'Muscle spasm', 'muscoril'),
  d('Tizanidine', 'Muscle spasm', 'sirdalud'),
  d('Chlorzoxazone', 'Muscle spasm'),
  // antibiotics, antifungals, antivirals
  d('Amoxicillin', 'Antibiotic', 'novamox', 'amoxil'),
  d('Amoxicillin-Clavulanate', 'Antibiotic', 'amoxicillin clavulanate', 'amoxicillin clavulanic acid', 'augmentin', 'clavam', 'amoxyclav', 'moxikind-cv'),
  d('Azithromycin', 'Antibiotic', 'azithral', 'azee'),
  d('Clarithromycin', 'Antibiotic', 'claribid'),
  d('Cefixime', 'Antibiotic', 'taxim-o'),
  d('Cefuroxime', 'Antibiotic', 'ceftum', 'zocef'),
  d('Cefpodoxime', 'Antibiotic', 'cepodem'),
  d('Ceftriaxone', 'Antibiotic', 'monocef'),
  d('Cephalexin', 'Antibiotic', 'sporidex'),
  d('Ciprofloxacin', 'Antibiotic', 'ciplox', 'cifran'),
  d('Levofloxacin', 'Antibiotic', 'levoflox', 'tavanic'),
  d('Ofloxacin', 'Antibiotic', 'zenflox'),
  d('Doxycycline', 'Antibiotic', 'doxt'),
  d('Metronidazole', 'Antibiotic', 'flagyl', 'metrogyl'),
  d('Nitrofurantoin', 'Urinary infection', 'furadantin'),
  d('Linezolid', 'Antibiotic', 'linospan'),
  d('Co-trimoxazole', 'Antibiotic', 'septran', 'bactrim'),
  d('Fluconazole', 'Antifungal', 'forcan'),
  d('Terbinafine', 'Antifungal', 'lamisil'),
  d('Albendazole', 'Worms', 'zentel'),
  d('Ivermectin', 'Parasites', 'ivecop'),
  d('Acyclovir', 'Antiviral', 'zovirax'),
  d('Oseltamivir', 'Antiviral', 'fluvir'),
  // acidity, stomach, nausea
  d('Pantoprazole', 'Acidity', 'pan 40', 'pantocid', 'pantop'),
  d('Omeprazole', 'Acidity', 'omez'),
  d('Rabeprazole', 'Acidity', 'razo'),
  d('Esomeprazole', 'Acidity', 'nexpro'),
  d('Lansoprazole', 'Acidity', 'lanzol'),
  d('Famotidine', 'Acidity', 'famocid'),
  d('Ranitidine', 'Acidity', 'zinetac', 'rantac'),
  d('Sucralfate', 'Stomach ulcer', 'sucrafil'),
  d('Domperidone', 'Nausea', 'domstal'),
  d('Ondansetron', 'Nausea', 'emeset', 'zofer'),
  d('Loperamide', 'Diarrhoea', 'eldoper'),
  d('Racecadotril', 'Diarrhoea', 'redotil'),
  d('Lactulose', 'Constipation', 'duphalac'),
  d('Bisacodyl', 'Constipation', 'dulcolax'),
  d('Drotaverine', 'Stomach cramps', 'drotin'),
  d('Dicyclomine', 'Stomach cramps', 'cyclopam'),
  // diabetes
  d('Metformin', 'Blood sugar', 'glycomet', 'glucophage'),
  d('Glimepiride', 'Blood sugar', 'amaryl', 'glimestar'),
  d('Gliclazide', 'Blood sugar', 'diamicron'),
  d('Sitagliptin', 'Blood sugar', 'januvia', 'istavel'),
  d('Vildagliptin', 'Blood sugar', 'galvus'),
  d('Teneligliptin', 'Blood sugar', 'zita'),
  d('Pioglitazone', 'Blood sugar', 'pioglar'),
  d('Empagliflozin', 'Blood sugar', 'jardiance'),
  d('Dapagliflozin', 'Blood sugar', 'forxiga'),
  d('Insulin', 'Blood sugar', 'mixtard', 'lantus', 'huminsulin', 'novorapid'),
  // blood pressure, heart, cholesterol, blood thinners
  d('Amlodipine', 'Blood pressure', 'amlong', 'amlip', 'amlokind'),
  d('Telmisartan', 'Blood pressure', 'telma', 'telsartan'),
  d('Losartan', 'Blood pressure', 'losar', 'repace'),
  d('Olmesartan', 'Blood pressure', 'olmezest'),
  d('Atenolol', 'Blood pressure', 'tenormin'),
  d('Metoprolol', 'Blood pressure', 'metolar', 'betaloc'),
  d('Bisoprolol', 'Blood pressure', 'concor'),
  d('Propranolol', 'Blood pressure', 'inderal'),
  d('Carvedilol', 'Heart', 'cardivas'),
  d('Nebivolol', 'Blood pressure', 'nebicard'),
  d('Ramipril', 'Blood pressure', 'cardace'),
  d('Enalapril', 'Blood pressure', 'envas'),
  d('Lisinopril', 'Blood pressure', 'listril'),
  d('Hydrochlorothiazide', 'Blood pressure'),
  d('Chlorthalidone', 'Blood pressure', 'thalitone'),
  d('Furosemide', 'Water tablet', 'lasix'),
  d('Torsemide', 'Water tablet', 'dytor'),
  d('Spironolactone', 'Water tablet', 'aldactone'),
  d('Nifedipine', 'Blood pressure', 'depin'),
  d('Diltiazem', 'Heart', 'dilzem'),
  d('Clonidine', 'Blood pressure', 'arkamin'),
  d('Isosorbide mononitrate', 'Angina', 'imdur', 'monotrate'),
  d('Nitroglycerin', 'Angina', 'sorbitrate', 'nitrocontin'),
  d('Ranolazine', 'Angina', 'ranozex'),
  d('Digoxin', 'Heart', 'lanoxin'),
  d('Amiodarone', 'Heart rhythm', 'cordarone'),
  d('Clopidogrel', 'Blood thinner', 'clopilet', 'plavix'),
  d('Ticagrelor', 'Blood thinner', 'brilinta'),
  d('Prasugrel', 'Blood thinner', 'prasita'),
  d('Warfarin', 'Blood thinner', 'acitrom', 'acenocoumarol'),
  d('Rivaroxaban', 'Blood thinner', 'xarelto'),
  d('Apixaban', 'Blood thinner', 'eliquis'),
  d('Atorvastatin', 'Cholesterol', 'atorva', 'lipitor'),
  d('Rosuvastatin', 'Cholesterol', 'rosuvas', 'crestor'),
  d('Simvastatin', 'Cholesterol', 'zocor'),
  d('Fenofibrate', 'Cholesterol', 'lipicard'),
  d('Ezetimibe', 'Cholesterol', 'ezetrol'),
  // thyroid
  d('Levothyroxine', 'Thyroid', 'thyronorm', 'eltroxin'),
  d('Carbimazole', 'Thyroid', 'neomercazole'),
  // breathing, allergy, steroids
  d('Cetirizine', 'Allergy', 'cetzine', 'okacet'),
  d('Levocetirizine', 'Allergy', 'levocet', 'xyzal'),
  d('Loratadine', 'Allergy', 'lorfast'),
  d('Fexofenadine', 'Allergy', 'allegra'),
  d('Chlorpheniramine', 'Allergy'),
  d('Hydroxyzine', 'Allergy', 'atarax'),
  d('Montelukast', 'Asthma / allergy', 'montair', 'singulair'),
  d('Salbutamol', 'Asthma', 'asthalin', 'ventolin'),
  d('Levosalbutamol', 'Asthma', 'levolin'),
  d('Budesonide', 'Asthma', 'budecort'),
  d('Ambroxol', 'Cough', 'ambrodil'),
  d('Bromhexine', 'Cough', 'bisolvon'),
  d('Dextromethorphan', 'Cough'),
  d('Theophylline', 'Asthma', 'deriphyllin'),
  d('Prednisolone', 'Steroid', 'wysolone'),
  d('Methylprednisolone', 'Steroid', 'medrol'),
  d('Dexamethasone', 'Steroid', 'dexona'),
  // nerves, sleep, mood
  d('Gabapentin', 'Nerve pain', 'gabapin', 'neurontin'),
  d('Pregabalin', 'Nerve pain', 'lyrica', 'pregalin'),
  d('Carbamazepine', 'Epilepsy / nerve pain', 'tegretol'),
  d('Phenytoin', 'Epilepsy', 'eptoin'),
  d('Levetiracetam', 'Epilepsy', 'levipil', 'keppra'),
  d('Sodium valproate', 'Epilepsy', 'valparin', 'valproate'),
  d('Amitriptyline', 'Nerve pain / mood', 'tryptomer'),
  d('Nortriptyline', 'Nerve pain / mood'),
  d('Escitalopram', 'Mood', 'nexito', 'lexapro'),
  d('Sertraline', 'Mood', 'zoloft'),
  d('Fluoxetine', 'Mood', 'fludac'),
  d('Clonazepam', 'Anxiety / epilepsy', 'rivotril', 'clonotril'),
  d('Alprazolam', 'Anxiety', 'alprax', 'restyl'),
  d('Zolpidem', 'Sleep', 'zolfresh'),
  d('Melatonin', 'Sleep'),
  d('Donepezil', 'Memory', 'aricept'),
  d('Levodopa-Carbidopa', 'Parkinson’s', 'syndopa'),
  d('Sumatriptan', 'Migraine', 'suminat'),
  d('Flunarizine', 'Migraine', 'sibelium'),
  d('Betahistine', 'Dizziness', 'vertin'),
  d('Cinnarizine', 'Dizziness', 'stugeron'),
  // bones, gout, joints, urinary
  d('Allopurinol', 'Gout', 'zyloric'),
  d('Febuxostat', 'Gout', 'febugood'),
  d('Colchicine', 'Gout'),
  d('Alendronate', 'Bone strength', 'fosamax'),
  d('Methotrexate', 'Arthritis', 'folitrax'),
  d('Hydroxychloroquine', 'Arthritis', 'hcqs'),
  d('Tamsulosin', 'Prostate', 'urimax', 'veltam'),
  d('Finasteride', 'Prostate', 'finpro'),
  d('Tranexamic acid', 'Bleeding', 'tranexa'),
  // vitamins and minerals
  d('Vitamin D3', 'Vitamin D', 'cholecalciferol', 'calcirol', 'uprise-d3'),
  d('Calcium', 'Bone strength', 'shelcal'),
  d('Folic acid', 'Vitamin', 'folvite'),
  d('Methylcobalamin', 'Vitamin B12', 'mecobalamin', 'nurokind'),
  d('Ferrous sulphate', 'Iron', 'fericip', 'dexorange'),
  d('Zinc', 'Supplement', 'zincovit'),
  d('Multivitamin', 'Supplement', 'becosules'),
];
