// Defines the background sync task at module load, so it exists when the OS wakes the app in the background.
import '@/sync/background';

import { DefaultTheme, Stack, ThemeProvider, useRouter, useSegments } from 'expo-router';
import { useFonts } from 'expo-font';
import * as SplashScreen from 'expo-splash-screen';
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import { useApp } from '@/app-state/store';
import { initCore } from '@/core';
import { initPrivacy } from '@/privacy';
import { startSyncTriggers } from '@/sync';
import { FONT_ASSETS } from '@/ui/fonts';
import { ToastHost } from '@/ui/toast';
import { useTheme } from '@/ui/theme';

SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const t = useTheme();
  const router = useRouter();
  const segments = useSegments();
  const { ready, onboarded, set } = useApp();
  const [fontsLoaded, fontError] = useFonts(FONT_ASSETS);

  // One-time startup: open the database and both shards, attach the Splitter.
  useEffect(() => {
    (async () => {
      try {
        await initCore();
        initPrivacy();
        // Demo build: every cold start begins on the onboarding, whatever was saved last run.
        set({ ready: true, onboarded: false });
      } catch (e) {
        console.warn('startup failed', e);
        set({ ready: true });
      }
    })();
  }, [set]);

  const shown = ready && (fontsLoaded || !!fontError);
  useEffect(() => {
    if (shown) void SplashScreen.hideAsync();
  }, [shown]);

  // Background work only runs for an onboarded user: connectivity/foreground/15-minute sync.
  useEffect(() => {
    if (!ready || !onboarded) return;
    return startSyncTriggers();
  }, [ready, onboarded]);

  // Onboarding gate.
  useEffect(() => {
    if (!ready) return;
    // (typed routes are regenerated by Metro; compare as a plain string so this compiles before that runs)
    const inOnboarding = (segments[0] as string | undefined) === 'onboarding';
    // a tick later, so the navigator has mounted before we navigate
    const h = setTimeout(() => {
      if (!onboarded && !inOnboarding) router.replace('/onboarding' as never);
      else if (onboarded && inOnboarding) router.replace('/' as never);
    }, 0);
    return () => clearTimeout(h);
  }, [ready, onboarded, segments, router]);

  if (!shown) return null;

  const navTheme = {
    ...DefaultTheme,
    colors: { ...DefaultTheme.colors, background: t.bg, card: t.wash, text: t.dark, border: t.border, primary: t.accentDark },
  };

  return (
    // Android forces edge-to-edge display, which stops the OS from resizing the window for the keyboard —
    // KeyboardProvider (react-native-keyboard-controller) is what makes Screen/Sheet's KeyboardAvoidingView
    // actually track the keyboard there, the same way it always has on iOS.
    <KeyboardProvider>
      <SafeAreaProvider>
        <ThemeProvider value={navTheme}>
          <StatusBar style="dark" />
          <Stack
            screenOptions={{
              headerShadowVisible: false,
              headerStyle: { backgroundColor: t.wash },
              headerTintColor: t.dark,
              headerTitleStyle: { fontFamily: 'Geist-Bold', fontSize: 18 },
              contentStyle: { backgroundColor: t.bg },
            }}>
            <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
            <Stack.Screen name="onboarding" options={{ headerShown: false, gestureEnabled: false }} />
            <Stack.Screen name="privacy" options={{ title: 'The Ledger' }} />
            <Stack.Screen name="settings" options={{ title: 'Settings' }} />
            <Stack.Screen name="diagnostics" options={{ title: 'Diagnostics' }} />
            <Stack.Screen name="dev" options={{ title: 'Developer tests' }} />
          </Stack>
          <ToastHost />
        </ThemeProvider>
      </SafeAreaProvider>
    </KeyboardProvider>
  );
}
