// Consultation lines used to check the doctor-only filter (soundsLikePatient in aftercare/engine.ts).
// Written by hand, not recorded: they show the filter's behaviour, not how it performs on real speech.

/** Doctor sentences. None may be set aside, except the bare acknowledgements in DOCTOR_ACK_ONLY. */
export const DOCTOR = [
  "Hello, please sit down.",
  "Hi, how are you?",
  "What is the problem?",
  "How long has this been going on?",
  "Do you get this pain at night?",
  "Any history of diabetes or high blood pressure?",
  "Are you allergic to any medicine?",
  "Open your mouth and say ah.",
  "Breathe in deeply.",
  "Let me check your blood pressure.",
  "Your BP is a little high today.",
  "The ECG looks normal.",
  "The report shows low haemoglobin.",
  "Your sugar is under control.",
  "There is mild swelling in the left knee.",
  "Take this tablet twice a day after food.",
  "Start Amlodipine 5 mg once daily in the morning.",
  "Continue the same medicines.",
  "Stop the painkiller for now.",
  "Take Paracetamol 650 mg if the fever comes back.",
  "Do not take it on an empty stomach.",
  "Avoid oily and spicy food.",
  "Drink plenty of water.",
  "Walk for thirty minutes every day.",
  "Apply this ointment twice a day.",
  "I am increasing the dose of Metformin.",
  "I'll write the tests for you.",
  "I want you to rest for three days.",
  "I have changed your tablet.",
  "I've increased your dose.",
  "Come back after ten days.",
  "Get a blood test done before the next visit.",
  "Repeat the X-ray next month.",
  "If the pain increases, call me.",
  "If you get chest pain go to the emergency.",
  "It is a mild viral infection.",
  "There is nothing to worry about.",
  "Your cholesterol has come down.",
  "You need to lose some weight.",
  "Take rest and sleep well.",
  "Yes, that is fine.",
  "Okay, continue those as they are.",
  "Right, that is normal.",
  "Good, the swelling has reduced.",
  "Next visit after one month.",
  "My advice is to avoid stairs.",
  "Pantoprazole 40 mg before breakfast.",
  "One tablet in the morning and one at night.",
  "Take it for five days.",
  "For ten days.",
  "If it does not improve, see a doctor.",
  "Consult a cardiologist if the pain returns.",
  "Please see your family doctor next week.",
  "If the pain gets worse, come back.",
  "When the fever comes, take Paracetamol.",
  "The pain is due to arthritis.",
  "The fever comes from a viral infection.",
  "The cough should settle in a week.",
  "Burning in the stomach is common with this tablet.",
  "The swelling will go down in two days.",
  "Right.",
  "Okay.",
  "Good.",
  "Fine, continue.",
  "Right, take it after food.",
  "Sir, your reports are normal.",
  "It started working as expected.",
  "It is a common problem.",
  "Take it for two weeks.",
  "After one week stop it.",
  "Three tablets a day.",
  "Two weeks later we will repeat the test.",
  "Last month your sugar was high.",
  "Yesterday I reviewed your report.",
  "Today your pressure is better.",
  "I have reviewed your report.",
  "I have noted your symptoms.",
  "I see you have been taking Dolo.",
  "You said the pain is at night.",
  "How are you feeling now?",
  "Tell me what you feel.",
  "Let me see the report.",
  "Show me the prescription.",
  "Do you smoke?",
  "No fever, no cough, that is good.",
];

/** A doctor saying just "Right." or "Okay." is set aside (nothing medical is lost, and Put back restores it). */
export const DOCTOR_ACK_ONLY = [
  "Right.",
  "Okay.",
];

/** Patient sentences. All should be set aside, except the known leaks below. */
export const PATIENT = [
  "Hello doctor.",
  "Hi, Dr.",
  "Good morning doctor.",
  "Yes doctor.",
  "Yes.",
  "Yeah.",
  "No.",
  "No, nothing else.",
  "Okay.",
  "Ok doctor.",
  "Haan doctor.",
  "Nahi doctor.",
  "Theek hai.",
  "Thank you doctor.",
  "Thanks.",
  "Hmm.",
  "Right.",
  "Sure doctor.",
  "Sorry doctor.",
  "Okay thank you sir.",
  "I have pain in my knee.",
  "I feel dizzy in the morning.",
  "My sugar was high yesterday.",
  "I am taking Dolo twice a day.",
  "I stopped the tablet last week.",
  "I've been having a cough for a week.",
  "I forgot to take the medicine.",
  "I cannot sleep at night.",
  "I get breathless on stairs.",
  "I'm very worried about my reports.",
  "My father also has diabetes.",
  "My back hurts a lot.",
  "It hurts when I bend.",
  "Can I take it with milk?",
  "Will I have to take this for life?",
  "Is it serious doctor?",
  "What should I eat?",
  "Can I go to work?",
  "Do you think I should stop it?",
  "The tablets are making me feel sick.",
  "The pain gets worse at night.",
  "Since last week.",
  "Three days.",
  "Two months.",
  "Dizzy in the morning.",
  "Chest pain after walking.",
  "Mostly in the lower back.",
  "Sometimes after food.",
  "Only at night.",
  "Yesterday evening.",
  "It started a week ago.",
  "The headache comes every afternoon.",
  "There is burning in my stomach.",
  "Little bit better now.",
  "Not much difference.",
  "Hello sir.",
  "Namaste doctor.",
  "Okay doctor, I will do that.",
  "Yes sir.",
  "Ji doctor.",
  "Two days.",
  "A week.",
  "Since morning.",
  "Since Monday.",
  "Last month.",
  "The cough started two days ago.",
  "Pain keeps coming at night.",
  "The fever comes every evening.",
  "Swelling got worse yesterday.",
  "It began after the fall.",
  "My leg is swollen.",
  "I am very tired.",
  "Nothing doctor.",
  "Not really.",
  "Yes, a little.",
  "Hmm okay.",
  "Alright.",
  "Acha.",
  "Fine doctor.",
  "Sorry, what?",
  "Sure, thank you.",
  "Thanks a lot.",
  "Is this okay doctor?",
  "What about my sugar?",
  "Do I need an injection?",
];

/** Patient sentences the wording rules cannot recognise: symptom fragments and short phrases with no first person. */
export const KNOWN_LEAKS = [
  "Dizzy in the morning.",
  "Chest pain after walking.",
  "Mostly in the lower back.",
  "Sometimes after food.",
  "Only at night.",
  "Little bit better now.",
  "Not much difference.",
  "Hello sir.",
];
